variables:
  DEBIAN_FRONTEND: noninteractive
  APT_GET_INSTALL: "apt-get install --no-install-recommends -q -y"

stages:
  - pre
  - build_test
  - deploy

.display_env:
  before_script:
    - date
    - uname -a
    - cat /etc/os-release

pre-commit:
  stage: pre
  image:
    name: alpine:edge
  extends: .display_env
  script:
    - apk add --no-cache git pre-commit
    - pre-commit --version
    - pre-commit run --all-files

pycodestyle:
  stage: pre
  image:
    name: alpine:latest
  extends: .display_env
  script:
    - apk add --no-cache py3-pycodestyle
    - pycodestyle --version
    - pycodestyle --show-source --show-pep8 --statistics --verbose .

ruff:
  stage: pre
  image:
    name: alpine:edge
  extends: .display_env
  script:
    - apk add --no-cache ruff
    - ruff check --unsafe-fixes --diff || echo "!!! todo !!!"
    - ruff check --output-format=full
    - ruff check --select NPY201 --fix --diff || echo "!!! todo !!!"
    - ruff check --select NPY201 --output-format=full

.debian_based_test:
  stage: build_test
  extends: .display_env
  script:
    - $APT_GET_INSTALL python3-hatchling python3-numpy python3-opencv python3-pip
    - pip3 install --break-system-packages --user .
    - ls -lah "$HOMe/.local/lib/python3.11/site-packages/"
    - export PATH=$PATH:~/.local/bin
    - detloclcheck_find_checkerboard -h
    - pip3 uninstall --break-system-packages DetLocLCheck

debian-latest:
  image:
    name: debian:latest
  extends: .debian_based_test

ubuntu-2224:
  image:
    name: ubuntu:22.04
  extends: .debian_based_test

ubuntu-2424:
  image:
    name: ubuntu:24.04
  extends: .debian_based_test
